### ISSUE TITLE
Bug in Advanced Fulltext Search: Wrong URL

### ISSUE THREAD

**Issue by mkasimd** [hibbitts-design/grav-theme-learn2-git-sync#10]
The advanced fulltext search directs to `/tntsearch` resulting in a `404 Not Found`. It should be `/search` instead. The advanced search is achieved by calling `/search/query:some keyword`.

**Comment by paulhibbitts** [comment]
Hi @mkasimd ,thanks for your issue report. This is intentional so that the advanced search and basic search can both be present at the same time. In the TNTSearch Plugin, you can customize the path for the search to tntsearch - as shown here:

![2019-05-03_09-43-07](https://user-images.githubusercontent.com/1812771/57152629-e0711d00-6d88-11e9-9df2-82baf909d2b3.png)

Since this theme is used by current users of the Learn2 with Git Sync skeleton (available at https://getgrav.org/) I wanted to try to maintain previous compatibility with the simple search plugin.

Do things work for you by changing the search route for the TNT plugin?

Thanks very much,
Paul

**Comment by mkasimd** [comment]
Hello @paulhibbitts Actually, I have both [SimpleSearch](https://github.com/getgrav/grav-plugin-simplesearch) and [TNT Search](https://github.com/trilbymedia/grav-plugin-tntsearch) enabled. Changing the template has not broken anything yet.

Changing the search route of [TNT Search](https://github.com/trilbymedia/grav-plugin-tntsearch) to `/tntsearch` makes the theme template work as is (thanks for showing this), but it seems like changing the URL is not necessary as I couldn't find any compatibility issues between both search plugins.

Was it the case in previous versions of the plugins or Grav?

**Comment by paulhibbitts** [comment]
Glad the search route change got things going!

At the time of adding TNTSearch to my Learn2 with Git Sync skeletons I ran into some issues, which is why I ended up with a custom URL. I'd be hesitant to make such changes now as you can imagine.

BTW, if Learn4 becomes a released theme I will be exploring a Git Sync version of that theme, which has built-in support for TNTSearch.

**Comment by mkasimd** [comment]
As we have resolved the issue and there's a valid reason for keeping your current search path, I'll close this issue now. By the way, it'd be nice if you could write into the README file that one should change the TNT Search configuration.

**Comment by paulhibbitts** [comment]
Thanks for the suggestion @mkasimd , I have now added a note about that in the ReadMe: https://github.com/hibbitts-design/grav-theme-learn2-git-sync#tntsearch-configuration
